export const myRequestedLeaves = [
  {
    id: "1",
    kuwaitPhoneNumber: "9192132",
    alternativePhoneNumber: "9192132",
    type: "Emergency",
    status: ["Pending", "Approved", "Rejected"],
    startData: new Date(),
    lastDate: new Date(),
    lastVacationDate: new Date(),
    totalDaysAvailed: "10",
    appliedBy: "John Doe",
    isYourLastVacationDelayed: "Yes",
    isFirstVacation: "Yes",
    isMoneyOwned: "Yes",
    dateOfMoneyOwned: new Date(),
    totalMoneyOwned: "1000",
    flightPreference: "Indigo",
    mentionDestinationTicked: "Yes",
    isReadyToPayTicketsVariable: "Yes",
    approvedByManager: "Yes",
    approvedByManagerId: "1",
    approvedByManagerOn: new Date(),
    approvedByHR: "Yes",
    approvedByHRId: "1",
    approvedByHROn: new Date(),
    emergencyDocId: "1",
  },
  {
    id: "2",
    kuwaitPhoneNumber: "9192132",
    alternativePhoneNumber: "9192132",
    type: "Regular Due Vacation",
    status: ["Pending", "Approved", "Rejected"],
    startData: new Date(),
    lastDate: new Date(),
    lastVacationDate: new Date(),
    totalDaysAvailed: "10",
    appliedBy: "Azeem Khan",
    isYourLastVacationDelayed: "Yes",
    isFirstVacation: "Yes",
    isMoneyOwned: "Yes",
    dateOfMoneyOwned: new Date(),
    totalMoneyOwned: "1000",
    flightPreference: "Indigo",
    mentionDestinationTicked: "Yes",
    isReadyToPayTicketsVariable: "Yes",
    approvedByManager: "Yes",
    approvedByManagerId: "1",
    approvedByManagerOn: new Date(),
    approvedByHR: "No",
    approvedByHRId: "1",
    approvedByHROn: new Date(),
    emergencyDocId: "1",
  },
];
